# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trokky < Formula
  desc "CLI for managing Trokky CMS instances"
  homepage "https://github.com/Trokky/cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Trokky/cli/releases/download/v0.2.0/trokky_0.2.0_darwin_amd64.tar.gz"
      sha256 "2b416fb3d9cac865e9d172d24616f32e96fd0431247bda5cf011756cf103a768"

      define_method(:install) do
        bin.install "trokky"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Trokky/cli/releases/download/v0.2.0/trokky_0.2.0_darwin_arm64.tar.gz"
      sha256 "8a36e5760193edf474331ee6e4031935ffd037ca9d8ff6a3cdedc1e4322e517d"

      define_method(:install) do
        bin.install "trokky"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Trokky/cli/releases/download/v0.2.0/trokky_0.2.0_linux_amd64.tar.gz"
      sha256 "3d194133d3289efa11594f941d1462200d6727a38abcd1aa308298c1fe140611"
      define_method(:install) do
        bin.install "trokky"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Trokky/cli/releases/download/v0.2.0/trokky_0.2.0_linux_arm64.tar.gz"
      sha256 "7d7b27ba194fe20583b997bc7677337c715b9960c23d48df7d64b37f13ae9b6e"
      define_method(:install) do
        bin.install "trokky"
      end
    end
  end

  test do
    system "#{bin}/trokky", "--version"
  end
end
