# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trokky < Formula
  desc "CLI for managing Trokky CMS instances"
  homepage "https://github.com/Trokky/cli"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Trokky/cli/releases/download/v0.1.1/trokky_0.1.1_darwin_amd64.tar.gz"
      sha256 "a455a06a8be87b2e209ebf627ade10dda41603022ce8146f49a1f9ec71c5f06c"

      define_method(:install) do
        bin.install "trokky"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Trokky/cli/releases/download/v0.1.1/trokky_0.1.1_darwin_arm64.tar.gz"
      sha256 "e0b744c9c44b116c08789dbd8c4d3b3bc6034b03fb4eb665ae6defec8116090a"

      define_method(:install) do
        bin.install "trokky"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Trokky/cli/releases/download/v0.1.1/trokky_0.1.1_linux_amd64.tar.gz"
      sha256 "b73ce5ba4e0f6b2f93f54782d43b9954b9690ac54a0aaf76f8b14b1e2ac9a302"
      define_method(:install) do
        bin.install "trokky"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Trokky/cli/releases/download/v0.1.1/trokky_0.1.1_linux_arm64.tar.gz"
      sha256 "2c1676458221a75c9991fefce5ffb64abdec4d37fea9d1f025d03ad6cdda3274"
      define_method(:install) do
        bin.install "trokky"
      end
    end
  end

  test do
    system "#{bin}/trokky", "--version"
  end
end
